// Generated by gencpp from file dmsgs/BehaviorInfo.msg
// DO NOT EDIT!


#ifndef DMSGS_MESSAGE_BEHAVIORINFO_H
#define DMSGS_MESSAGE_BEHAVIORINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace dmsgs
{
template <class ContainerAllocator>
struct BehaviorInfo_
{
  typedef BehaviorInfo_<ContainerAllocator> Type;

  BehaviorInfo_()
    : current_role(0)
    , skill()
    , dest()
    , final_dest()
    , attack_target()
    , save_image(false)
    , more_lines(false)
    , vision_correct_yaw(false)
    , attack_right(false)
    , team_play_state(0)
    , kicker_id(0)
    , team_play_priority(false)
    , mates_online()
    , time_since_last_kick(0.0)  {
      mates_online.assign(false);
  }
  BehaviorInfo_(const ContainerAllocator& _alloc)
    : current_role(0)
    , skill(_alloc)
    , dest(_alloc)
    , final_dest(_alloc)
    , attack_target(_alloc)
    , save_image(false)
    , more_lines(false)
    , vision_correct_yaw(false)
    , attack_right(false)
    , team_play_state(0)
    , kicker_id(0)
    , team_play_priority(false)
    , mates_online()
    , time_since_last_kick(0.0)  {
  (void)_alloc;
      mates_online.assign(false);
  }



   typedef uint8_t _current_role_type;
  _current_role_type current_role;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _skill_type;
  _skill_type skill;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _dest_type;
  _dest_type dest;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _final_dest_type;
  _final_dest_type final_dest;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _attack_target_type;
  _attack_target_type attack_target;

   typedef uint8_t _save_image_type;
  _save_image_type save_image;

   typedef uint8_t _more_lines_type;
  _more_lines_type more_lines;

   typedef uint8_t _vision_correct_yaw_type;
  _vision_correct_yaw_type vision_correct_yaw;

   typedef uint8_t _attack_right_type;
  _attack_right_type attack_right;

   typedef uint8_t _team_play_state_type;
  _team_play_state_type team_play_state;

   typedef uint8_t _kicker_id_type;
  _kicker_id_type kicker_id;

   typedef uint8_t _team_play_priority_type;
  _team_play_priority_type team_play_priority;

   typedef boost::array<uint8_t, 6>  _mates_online_type;
  _mates_online_type mates_online;

   typedef float _time_since_last_kick_type;
  _time_since_last_kick_type time_since_last_kick;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ROLE_STRIKER)
  #undef ROLE_STRIKER
#endif
#if defined(_WIN32) && defined(ROLE_DEFENDER)
  #undef ROLE_DEFENDER
#endif
#if defined(_WIN32) && defined(ROLE_SUPPORTER)
  #undef ROLE_SUPPORTER
#endif
#if defined(_WIN32) && defined(ROLE_GOALIE)
  #undef ROLE_GOALIE
#endif
#if defined(_WIN32) && defined(ROLE_OTHER)
  #undef ROLE_OTHER
#endif

  enum {
    ROLE_STRIKER = 1u,
    ROLE_DEFENDER = 2u,
    ROLE_SUPPORTER = 3u,
    ROLE_GOALIE = 4u,
    ROLE_OTHER = 5u,
  };


  typedef boost::shared_ptr< ::dmsgs::BehaviorInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dmsgs::BehaviorInfo_<ContainerAllocator> const> ConstPtr;

}; // struct BehaviorInfo_

typedef ::dmsgs::BehaviorInfo_<std::allocator<void> > BehaviorInfo;

typedef boost::shared_ptr< ::dmsgs::BehaviorInfo > BehaviorInfoPtr;
typedef boost::shared_ptr< ::dmsgs::BehaviorInfo const> BehaviorInfoConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dmsgs::BehaviorInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dmsgs::BehaviorInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dmsgs::BehaviorInfo_<ContainerAllocator1> & lhs, const ::dmsgs::BehaviorInfo_<ContainerAllocator2> & rhs)
{
  return lhs.current_role == rhs.current_role &&
    lhs.skill == rhs.skill &&
    lhs.dest == rhs.dest &&
    lhs.final_dest == rhs.final_dest &&
    lhs.attack_target == rhs.attack_target &&
    lhs.save_image == rhs.save_image &&
    lhs.more_lines == rhs.more_lines &&
    lhs.vision_correct_yaw == rhs.vision_correct_yaw &&
    lhs.attack_right == rhs.attack_right &&
    lhs.team_play_state == rhs.team_play_state &&
    lhs.kicker_id == rhs.kicker_id &&
    lhs.team_play_priority == rhs.team_play_priority &&
    lhs.mates_online == rhs.mates_online &&
    lhs.time_since_last_kick == rhs.time_since_last_kick;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dmsgs::BehaviorInfo_<ContainerAllocator1> & lhs, const ::dmsgs::BehaviorInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dmsgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dmsgs::BehaviorInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dmsgs::BehaviorInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dmsgs::BehaviorInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dmsgs::BehaviorInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dmsgs::BehaviorInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dmsgs::BehaviorInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dmsgs::BehaviorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e56328e1dc36ea6c8350f1e6761eba1a";
  }

  static const char* value(const ::dmsgs::BehaviorInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe56328e1dc36ea6cULL;
  static const uint64_t static_value2 = 0x8350f1e6761eba1aULL;
};

template<class ContainerAllocator>
struct DataType< ::dmsgs::BehaviorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dmsgs/BehaviorInfo";
  }

  static const char* value(const ::dmsgs::BehaviorInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dmsgs::BehaviorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Decision Making\n"
"uint8 current_role\n"
"string skill\n"
"\n"
"# Destination\n"
"geometry_msgs/Vector3 dest\n"
"geometry_msgs/Vector3 final_dest\n"
"geometry_msgs/Vector3 attack_target\n"
"\n"
"# Misc\n"
"bool save_image\n"
"bool more_lines\n"
"bool vision_correct_yaw\n"
"\n"
"# ROLE\n"
"uint8 ROLE_STRIKER    = 1\n"
"uint8 ROLE_DEFENDER   = 2\n"
"uint8 ROLE_SUPPORTER  = 3\n"
"uint8 ROLE_GOALIE     = 4\n"
"uint8 ROLE_OTHER      = 5\n"
"\n"
"bool attack_right\n"
"\n"
"# Playing state of robot\n"
"uint8 team_play_state\n"
"\n"
"# Priority of current behavior\n"
"uint8 kicker_id\n"
"bool team_play_priority\n"
"\n"
"bool[6] mates_online\n"
"\n"
"float32 time_since_last_kick\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::dmsgs::BehaviorInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dmsgs::BehaviorInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_role);
      stream.next(m.skill);
      stream.next(m.dest);
      stream.next(m.final_dest);
      stream.next(m.attack_target);
      stream.next(m.save_image);
      stream.next(m.more_lines);
      stream.next(m.vision_correct_yaw);
      stream.next(m.attack_right);
      stream.next(m.team_play_state);
      stream.next(m.kicker_id);
      stream.next(m.team_play_priority);
      stream.next(m.mates_online);
      stream.next(m.time_since_last_kick);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BehaviorInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dmsgs::BehaviorInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dmsgs::BehaviorInfo_<ContainerAllocator>& v)
  {
    s << indent << "current_role: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.current_role);
    s << indent << "skill: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.skill);
    s << indent << "dest: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.dest);
    s << indent << "final_dest: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.final_dest);
    s << indent << "attack_target: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.attack_target);
    s << indent << "save_image: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.save_image);
    s << indent << "more_lines: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.more_lines);
    s << indent << "vision_correct_yaw: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vision_correct_yaw);
    s << indent << "attack_right: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.attack_right);
    s << indent << "team_play_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.team_play_state);
    s << indent << "kicker_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.kicker_id);
    s << indent << "team_play_priority: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.team_play_priority);
    s << indent << "mates_online[]" << std::endl;
    for (size_t i = 0; i < v.mates_online.size(); ++i)
    {
      s << indent << "  mates_online[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.mates_online[i]);
    }
    s << indent << "time_since_last_kick: ";
    Printer<float>::stream(s, indent + "  ", v.time_since_last_kick);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DMSGS_MESSAGE_BEHAVIORINFO_H
